### ISSUE TITLE
set max

### ISSUE THREAD

**Issue by Luke24236** [Xquiset/SetHomes#12]
i have this plugin installed and is working. I aslo have vault and luck perms and i have many groups made for my players on luck perms and when i do /setmax (the group name i did for the luck perms) it says "the group name you entered does not exist". I made sure the group has the homes.setmax permission on true and it still doesnt work. I been going at this for so long and its stating to be a waste of my time, Please someone help!

**Comment by Xquiset** [comment]
Hello,

Sorry for the delay in reply. Could you please post your config.yml. This can be found by navigating to plugins > SetHomes > config.yml starting from your servers root directory. I believe that the message is actually a bug, and should really be giving you a success message.

Best Regards,
Xquiset

**Comment by Xquiset** [comment]
Hello,

I have uploaded a new version of the plugin today that fixes two issues. One being this incorrect message, and the other fixes named homes not being cleansed of non-alphanumeric values.

Best Regards,
Xquiset
