### ISSUE TITLE
Lack of input validation

### ISSUE THREAD

**Issue by camfsd** [Xquiset/SetHomes#15]
Creating non-alphanumeric homes breaks the plugin.

The plugin could do with validation to ensure home names are alphanumeric.

**Comment by Xquiset** [comment]
Hello,

Thank you for bringing this to my attention. I have uploaded a new version of the plugin (SetHomes V1.3.0) today that fixes this issue. Please let me know if there is anything else I can help with.

Best Regards,
Xquiset
