### ISSUE TITLE
Ability to delete all homes in specific world

### ISSUE THREAD

**Issue by oranges13** [Xquiset/SetHomes#8]
Hello! I was wondering if this plugin provides the ability to delete all player homes in a specific world. Some context:

- Our server has monthly resetting resource worlds, including the nether & end.
- Players are allowed to set homes here during the month (we currently use EssentialsX)
- We require players to delete any pre-existing homes when the world is reset monthly, but we have to take this on faith. A player with a home in the end, for example, could tp to the islands without having to beat the dragon.

I'm looking for a solution that would allow us to curate player homes in specific worlds on a regular basis for these reasons. Thanks for any suggestions or assistance!

**Comment by Xquiset** [comment]
Hello,

Sorry for the much delayed reply. I will add this as a feature request for the next update.

Best Regards,
Xquiset
